# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: |
   dotnet add Okuyami.WebServices.Tests package coverlet.msbuild
   dotnet add Okuyami.WebApp.Tests package coverlet.msbuild
  displayName: 'Install Tools for Coverage'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: coverlet "**/pipelines-dotnet-core-test.dll" --target "dotnet" --targetargs "test --no-build" --format opencover
  displayName: 'Coverlet code coverage'

- task: SonarQubePrepare@4
  displayName: 'Prepare analysis on SonarQube'
  inputs:
    SonarQube: haihnsonarqube
    projectKey: 'pipeline-dotnet-core'
    projectName: 'pipeline-dotnet-core'
    extraProperties: '/d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" /d:sonar.coverage.exclusions="**Tests*.cs, **.ts, **.js"'
    
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*test/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1

- task: SonarQubeAnalyze@4
  displayName: 'Run Code Analysis'

- task: SonarQubePublish@4
  displayName: 'Publish Quality Gate Result'
  
- task: AzureRmWebAppDeployment@4
  inputs:
    azureSubscription: 'Visual Studio Enterprise(0e10be42-fc35-45f1-9c83-d19b6f65c352)'
    WebAppName: 'pipelines-dotnet-core-test'
    Package: $(System.ArtifactsDirectory)/**/*.zip