# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: Hosted VS2017

variables:
  buildConfiguration: 'Release'

steps:
- script: |
    dotnet add pipelines-dotnet-core-test package coverlet.msbuild
    dotnet add pipelines-dotnet-core-test-2 package coverlet.msbuild
  displayName: 'Install Tools for Coverage'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: test
    projects: '**/*[Tt]est*/*.csproj'
    arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude=[**.Views]* --configuration $(BuildConfiguration)'

- task: reportgenerator@4
  displayName: ReportGenerator
  inputs:
    reports: '$(System.DefaultWorkingDirectory)\**\coverage.opencover.xml'
    targetdir: '$(Common.TestResultsDirectory)\Coverage\Reports'

- task: SonarQubePrepare@4
  displayName: 'Prepare analysis on SonarQube'
  inputs:
    SonarQube: haihnsonarqube
    projectKey: 'pipeline-dotnet-core'
    projectName: 'pipeline-dotnet-core'
    extraProperties: |
      sonar.cs.opencover.reportsPaths=$(Common.TestResultsDirectory)\Coverage\Reports\coverage.opencover.xml
      sonar.coverage.exclusions=**Tests*.cs, **.ts, **.js
    
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: SonarQubeAnalyze@4
  displayName: 'Run Code Analysis'

- task: SonarQubePublish@4
  displayName: 'Publish Quality Gate Result'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  
- task: AzureRmWebAppDeployment@4
  inputs:
    azureSubscription: 'Visual Studio Enterprise(0e10be42-fc35-45f1-9c83-d19b6f65c352)'
    WebAppName: 'pipelines-dotnet-core-test'
    Package: $(System.ArtifactsDirectory)/**/*.zip